---
title: "Monthly Portfolio Rebalancing"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r comment="", eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
require(quantmod); require(PerformanceAnalytics)
# Rank.R contains functions for different ranking algorithms
source("./stck_rscripts/Rank.R")

# monthly-fun.R contains functions for prepping monthly data
source("./stck_rscripts/monthly-fun.R")

symbols<- c(
        "BIL", 
        "AGG", 
        "EFA", 
        "SPY", 
        "VTIP", 
        "VUSTX",
        "JNK",
        "VONV",
        "VONG",
        "VTWG",
        "VTWV",
        "EEM",
        "VNQ",
        "DJP"
)

# get data for the symbols
getSymbols(symbols, from="2012-01-01")

# create an xts object of monthly adjusted close prices
symbols.close <- monthlyPrices(symbols)


# create an xts object of the symbol ranks
sym.rank1 <- applyRank(x=symbols.close, rankFun=singleROC)
sym.rank2 <- applyRank(x=symbols.close, rankFun=ave3ROC, n=c(1, 3, 6, 9, 12))
# this is an important step in naming the columns, e.g. XLY.Rank
# the "Rank" column is used as the trade signal (similar to an indicator)
# in the qstratRank function
colnames(sym.rank1) <- gsub(".Adjusted", "", colnames(sym.rank1))
colnames(sym.rank2) <- gsub(".Adjusted", "", colnames(sym.rank2))

# ensure the order of order symbols is equal to the order of columns 
# in symbols.close
stopifnot(all.equal(gsub(".Adjusted", "", colnames(symbols.close)), symbols))

sym.rank1 <- as.xts(t(apply(sym.rank1, 1, rank)), dateFormat="Date")
sym.rank2 <- as.xts(t(apply(sym.rank2, 1, rank)), dateFormat="Date")

sym.names <- c("Interest Income Index",
               "Investment Grade Bond Index",
               "International Equity Index",
               "S&P 500 Index",
               "Inflation Protected Treasury Index",
               "Long-term Treasury Index",
               "High Yield Corporate Bond Index",
               "Large Company Value Index",
               "Large Company Growth Index",
               "Small Company Value Index",
               "Small Company Growth Index",
               "Emerging Market Stock Index",
               "Real Estate Investment Trust Index",
               "Commodities Index")

sym.rank1 <- data.frame(cbind(sym.names,t(sym.rank1)[,nrow(sym.rank1)]))
colnames(sym.rank1) <- c("FUND", "RANK")

sym.rank1$RANK <- as.vector(sym.rank1$RANK)
sym.rank1$RANK <- as.numeric(sym.rank1$RANK)

sym.rank2 <- data.frame(cbind(sym.names,t(sym.rank2)[,nrow(sym.rank2)]))
colnames(sym.rank2) <- c("FUND", "RANK")

sym.rank2$RANK <- as.vector(sym.rank2$RANK)
sym.rank2$RANK <- as.numeric(sym.rank2$RANK)

res.1month <- head(sym.rank1[order(sym.rank1$RANK),], n=5L)
res.3month <- head(sym.rank2[order(sym.rank2$RANK),], n=5L)

```

```{r echo=FALSE, warning=FALSE, results='asis', eval=TRUE}
library(xtable)
options(xtable.comment = FALSE)

xtable (res.3month, caption = "Average of 1, 3, 6, 9, 12 Month ROC Ranking")
xtable (res.1month, floating = FALSE, caption = "1 Month Return Ranking")
```

\pagebreak

```{r echo=FALSE, warning=FALSE, results='asis', out.width="35%"}
topSyms1 <- c(colnames(t(res.3month)))

for(sym in topSyms1) {
        x <- get(sym)
        x <- to.monthly(x, indexAt = 'lastof', drop.time = TRUE)
        indexFormat(x) <- '%Y-%m-%d'
        colnames(x) <- gsub("x", sym, colnames(x))
        assign(sym, x)

        chartSeries(x, theme = chartTheme('white', bg.col = 'white', 
                                          up.col = 'white', dn.col = 'black'),
                    type = c('candles'), multi.col = FALSE, TA = 'addSMA(n=10)',
                    major.ticks = 'months', name = as.character(sym))
}

topSyms2 <- c(colnames(t(res.1month)))

for(sym in topSyms2) {
        x <- get(sym)
        x <- to.monthly(x, indexAt = 'lastof', drop.time = TRUE)
        indexFormat(x) <- '%Y-%m-%d'
        colnames(x) <- gsub("x", sym, colnames(x))
        assign(sym, x)
        
        chartSeries(x, theme = chartTheme('white', bg.col = 'white',
                                          up.col = 'white', dn.col = 'black'),
                    type = c('candles'), multi.col = FALSE, TA = 'addSMA(n=10)',
                    major.ticks = 'months', name = as.character(sym))
}
```
